image: docker:latest

services:
  - docker:dind

test:
  stage: build
  script:
    - docker build -t test -f docker_files/Dockerfile_slim .
    - docker run test pytest /tmp/train-container-library/train_lib
