version: '3.8'

volumes:
  blaze-data:

services:
  blaze-fhir:
    image: "samply/blaze:0.11.0"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
    ports:
        - "8080:8080"
    volumes:
      - "blaze-data:/app/data"
